#AndroidEnv Prevent `EmulatorLauncher` from trying to kill process twice.
`EmulatorLauncher` tries to kill the Android Emulator process when
`.close()`ed, but if users try to explicitly call `AndroidEnv.close()` (which
is the correct and expected behavior from `dm_env`'s perspective), we get the
following error:

```
I0309 19:07:32.047658  677927 emulator_launcher.py:131] Closing the emulator...
I0309 19:07:32.047745  677927 emulator_launcher.py:155] Shutting down the emulator...
Exception ignored in: <bound method EmulatorLauncher.__del__ of <android_env.components.emulator_launcher.EmulatorLauncher object at 0x7f6ed1450630>>
Traceback (most recent call last):
  File "/usr/local/google/_blaze_kenjitoyama/bff7df072e7f3ad8e5a1e9aee2c113c6/execroot/google3/blaze-out/k8-opt/bin/learning/deepmind/rl/environments/android/example_scripts/run_random_agent_no_env_loader.runfil
es/google3/third_party/py/android_env/components/emulator_launcher.py", line 143, in __del__
    self.close()
  File "/usr/local/google/_blaze_kenjitoyama/bff7df072e7f3ad8e5a1e9aee2c113c6/execroot/google3/blaze-out/k8-opt/bin/learning/deepmind/rl/environments/android/example_scripts/run_random_agent_no_env_loader.runfil
es/google3/third_party/py/android_env/components/emulator_launcher.py", line 132, in close
    self._shutdown()
  File "/usr/local/google/_blaze_kenjitoyama/bff7df072e7f3ad8e5a1e9aee2c113c6/execroot/google3/blaze-out/k8-opt/bin/learning/deepmind/rl/environments/android/example_scripts/run_random_agent_no_env_loader.runfil
es/google3/third_party/py/android_env/components/emulator_launcher.py", line 156, in _shutdown
    self._emulator.kill(signal.SIGKILL)
  File "/usr/local/google/_blaze_kenjitoyama/bff7df072e7f3ad8e5a1e9aee2c113c6/execroot/google3/blaze-out/k8-opt/bin/learning/deepmind/rl/environments/android/example_scripts/run_random_agent_no_env_loader.runfiles/google3/third_party/py/pexpect/popen_spawn.py", line 184, in kill
    os.kill(self.proc.pid, sig)
ProcessLookupError: [Errno 3] No such process
```

This CL simply sets the pexpect variable to `None` so that if that's called
again, we do not try to send another `KILL` signal to the underlying process.

PiperOrigin-RevId: 361884718